version: "3.8"

services:
  db:
    image: postgres:latest
    hostname: db
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=app_database
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d app_database'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
