version: "3.9"

services:
  #Application
  api1:
    image: nicktoon21/go-store-cars:latest
    hostname: api01
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_NAME=app_database
      - DB_PORT=5432
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    networks:
      - app-network

  api2:
    image: nicktoon21/go-store-cars:latest
    hostname: api02
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_NAME=app_database
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    networks:
      - app-network

  #Load Balancer
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - app-network

  #Database
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=app_database
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d app_database'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
